Add Redis Housekeeping
JamFactoryApp/jamfactory-backend pull request #80
Opened 2021-04-14 16:12 UTC by exp625

Fixes #79

2021-04-14 16:12 UTC, exp625 commented
This was easier than I thought

2021-04-14 18:02 UTC, DrJoLe commented on pkg/cache/redis.go
> +	defaultTTL       = 60 * 60 * 24 // Cache entries should update every day
Please use `go fmt`

2021-04-14 18:03 UTC, DrJoLe commented on api/store/redis.go
> +	cookieMaxAge			   = 60 * 60 * 24 * 7 // Cookie can last for 7 days
Please use `go fmt`

2021-04-14 18:03 UTC, DrJoLe requested changes
See comments

2021-04-14 18:08 UTC, DrJoLe requested changes

2021-04-14 18:08 UTC, DrJoLe commented on api/store/redis.go
> +	cookieMaxAge			   = 60 * 60 * 24 * 7 // Cookie can last for 7 days
Please use `go fmt`

2021-04-14 18:08 UTC, DrJoLe commented on pkg/cache/redis.go
> +	defaultTTL       = 60 * 60 * 24 // Cache entries should update every day
Please use `go fmt`

2021-04-15 10:39 UTC, DrJoLe approved these changes
Thanks

2021-04-15 10:40 UTC, merged